### ISSUE TITLE
issue:Cannot bind to the new display member.

### ISSUE THREAD

**Issue by bestmmk** [Zimgineering/WorkDone#1]
System.ArgumentException: Cannot bind to the new display member.
Parameter name: newDisplayMember
`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Cannot bind to the new display member.
Parameter name: newDisplayMember
   at System.Windows.Forms.ListControl.SetDataConnection(Object newDataSource, BindingMemberInfo newDisplayMember, Boolean force)
   at System.Windows.Forms.ListControl.set_ValueMember(String value)
   at WorkDone.Form1.SetupLayout() in D:\My Games\rbcn\Plugins\WorkDone\WorkDone.cs:line 150
   at WorkDone.Form1.Form1_Load(Object sender, EventArgs e) in D:\My Games\rbcn\Plugins\WorkDone\WorkDone.cs:line 183
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
RebornBuddy
    Assembly Version: 1.0.399.0
    Win32 Version: 1.0.399
    CodeBase: file:///D:/My%20Games/rbcn/RebornBuddy.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
{181ff401-d53e-46fd-b105-fdc30f6c28c8}
    Assembly Version: 0.0.0.0
    Win32 Version: 1.0.399
    CodeBase: file:///D:/My%20Games/rbcn/RebornBuddy.exe
----------------------------------------
Clio.Localization
    Assembly Version: 1.0.399.0
    Win32 Version: 1.0.399
    CodeBase: file:///D:/My%20Games/rbcn/Clio.Localization.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
GreyMagic
    Assembly Version: 1.0.41.0
    Win32 Version: 
    CodeBase: file:///D:/My%20Games/rbcn/GreyMagic.DLL
----------------------------------------
Buddy.Auth
    Assembly Version: 1.0.164.39
    Win32 Version: 1.0.399
    CodeBase: file:///D:/My%20Games/rbcn/RebornBuddy.exe
----------------------------------------
System.Runtime.Caching
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Caching/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Caching.dll
----------------------------------------
Microsoft.CodeDom.Providers.DotNetCompilerPlatform
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.20820.0
    CodeBase: file:///D:/My%20Games/rbcn/Microsoft.CodeDom.Providers.DotNetCompilerPlatform.DLL
----------------------------------------
SlimDX
    Assembly Version: 4.0.13.43
    Win32 Version: 
    CodeBase: file:///D:/My%20Games/rbcn/SlimDX.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Clio.Localization.resources
    Assembly Version: 1.0.399.0
    Win32 Version: 1.0.399
    CodeBase: file:///D:/My%20Games/rbcn/zh-CN/Clio.Localization.resources.DLL
----------------------------------------
PresentationFramework.Aero
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero.dll
----------------------------------------
PresentationFramework-SystemXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
PresentationFramework-SystemXmlLinq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXmlLinq/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXmlLinq.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
PresentationUI
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationUI/v4.0_4.0.0.0__31bf3856ad364e35/PresentationUI.dll
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
Quest Behaviors_1299486942
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/Quest%20Behaviors_1299486942.dll
----------------------------------------
Fertilizer_2067528575
    Assembly Version: 1.0.399.0
    Win32 Version: 1.0.399
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/Fertilizer_2067528575.dll
----------------------------------------
Lisbeth_199229823
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/Lisbeth_199229823.dll
----------------------------------------
ATB_1608140701
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/ATB_1608140701.dll
----------------------------------------
ChocoboTrainer_1069633283
    Assembly Version: 1.0.399.0
    Win32 Version: 1.0.399
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/ChocoboTrainer_1069633283.dll
----------------------------------------
Deepdive_962030321
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/Deepdive_962030321.dll
----------------------------------------
Deep Dungeon_342886386
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/Deep%20Dungeon_342886386.dll
----------------------------------------
HouseBuyer_803314893
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/HouseBuyer_803314893.dll
----------------------------------------
RaidBro_2043565806
    Assembly Version: 1.0.399.0
    Win32 Version: 1.0.399
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/RaidBro_2043565806.dll
----------------------------------------
FishAssist_1243379179
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/FishAssist_1243379179.dll
----------------------------------------
Retainers_1744209538
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/Retainers_1744209538.dll
----------------------------------------
TripleTriHard_107772906
    Assembly Version: 1.0.399.0
    Win32 Version: 1.0.399
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/TripleTriHard_107772906.dll
----------------------------------------
PresentationFramework-SystemData
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemData/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemData.dll
----------------------------------------
AlertnReply_45756301
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/AlertnReply_45756301.dll
----------------------------------------
Trust_448851256
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/Trust_448851256.dll
----------------------------------------
Mew_559222369
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/Mew_559222369.dll
----------------------------------------
QuestDev_735115274
    Assembly Version: 1.0.399.0
    Win32 Version: 1.0.399
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/QuestDev_735115274.dll
----------------------------------------
RebornConsole_1657048754
    Assembly Version: 1.0.399.0
    Win32 Version: 1.0.399
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/RebornConsole_1657048754.dll
----------------------------------------
Rebornbuddy3DOverlay_1193392162
    Assembly Version: 1.0.399.0
    Win32 Version: 1.0.399
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/Rebornbuddy3DOverlay_1193392162.dll
----------------------------------------
Cyril_1460198081
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/Cyril_1460198081.dll
----------------------------------------
WorkDone_1792566142
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/WorkDone_1792566142.dll
----------------------------------------
SideStep_448972446
    Assembly Version: 1.0.399.0
    Win32 Version: 1.0.399.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/SideStep_448972446.dll
----------------------------------------
ExBuddy_1738819290
    Assembly Version: 5.1.7464.22536
    Win32 Version: 5.1.0.2
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/ExBuddy_1738819290.dll
----------------------------------------
Microsoft.Scripting
    Assembly Version: 1.1.0.20
    Win32 Version: 1.1.0.20
    CodeBase: file:///D:/My%20Games/rbcn/Microsoft.Scripting.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
技术攻略_1133606367
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/%E6%8A%80%E6%9C%AF%E6%94%BB%E7%95%A5_1133606367.dll
----------------------------------------
Kupo_2134246468
    Assembly Version: 1.0.399.0
    Win32 Version: 1.0.399
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/Kupo_2134246468.dll
----------------------------------------
Lisbeth.Reborn
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/BotBases/Lisbeth/Lisbeth.Reborn.dll
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
Shinra2_1585372610
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/Shinra2_1585372610.dll
----------------------------------------
Mew
    Assembly Version: 2.3.7358.33727
    Win32 Version: 2.3.1.0
    CodeBase: file:///D:/My%20Games/rbcn/Plugins/Mew/Mew.dll
----------------------------------------
Mew.resources
    Assembly Version: 2.3.7358.33727
    Win32 Version: 2.3.1.0
    CodeBase: file:///D:/My%20Games/rbcn/Plugins/Mew/zh-CN/Mew.resources.DLL
----------------------------------------
Cyril
    Assembly Version: 1.2.1.1
    Win32 Version: 1.2.1.1
    CodeBase: file:///D:/My%20Games/rbcn/Plugins/Cyril/Cyril.dll
----------------------------------------
技术攻略
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/Routines/%E6%8A%80%E6%9C%AF%E6%94%BB%E7%95%A5/%E6%8A%80%E6%9C%AF%E6%94%BB%E7%95%A5.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
System.Data.SqlXml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.SqlXml/v4.0_4.0.0.0__b77a5c561934e089/System.Data.SqlXml.dll
----------------------------------------
System.Web.ApplicationServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.ApplicationServices/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.ApplicationServices.dll
----------------------------------------
Microsoft.Build.Framework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.Build.Framework/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.Build.Framework.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.IdentityModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Runtime.DurableInstancing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.DurableInstancing/v4.0_4.0.0.0__31bf3856ad364e35/System.Runtime.DurableInstancing.dll
----------------------------------------
System.Web.Services
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------
Quest Behaviors_876703278
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/Quest%20Behaviors_876703278.dll
----------------------------------------
RunCode_2294845817637272163203076905
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/My%20Games/rbcn/CompiledAssemblies/RunCode_2294845817637272163203076905.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

`

**Comment by Zimgineering** [comment]
Oops I didn't see the issue was open, is this still a problem? I've pushed some updates since this was posted.

**Comment by bestmmk** [comment]
when i posted this issues, im flagged by github with mistake
now the issue was sloved.
